If you don't know anything about building websites, that's fine. Here are the basic steps to follow:

### Step 1 {-}
**Sign up / sign in to [Github](https://github.com/).** Git is a version control system designed for computer programmers.
Github is an online platform that uses Git, and can help with all kinds of collaborative projects.

### Step 2 {-}
**Create an [Issue](https://github.com/mdeamico/traffic-modeling/issues)** describing your idea for new content or content to change.
The issue tracker provides a forum for the community to discuss.
<hr>

### Next Steps {-}
You can stop after step 2 if you just want to participate and discuss ideas.
The next steps are if you want to create or edit content on this website.

### Step 3 {-}
**Create a [Fork](https://guides.github.com/activities/forking/) of the website.** This copies the website content to your Github account.
You can then freely implement the changes discussed in the issue you opened in Step 2 without worry of messing up the original website.

 - All website content is written in [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet), an easy-to-learn syntax that does not require expert programming skills!
 - TODO: link to additional tutorials about editing this project

### Step 4 {-}
**Submit a [Pull Request](https://guides.github.com/activities/forking/#making-a-pull-request).** The project maintainers will review your changes. After any discussion, you may be asked to make revisions.
After revisions, the final version of your changes will be *pulled* into the website as appropriate.
<hr>

## Code of Conduct {- #code-of-conduct}
### Our Pledge {-}

In the interest of fostering an open and welcoming environment, we as
contributors and maintainers pledge to making participation in our project and
our community a harassment-free experience for everyone, regardless of age, body
size, disability, ethnicity, gender identity and expression, level of experience,
nationality, personal appearance, race, religion, or sexual identity and
orientation.

### Our Standards {-}

Examples of behavior that contributes to creating a positive environment
include:

* Using welcoming and inclusive language
* Being respectful of differing viewpoints and experiences
* Gracefully accepting constructive criticism
* Focusing on what is best for the community
* Showing empathy towards other community members

Examples of unacceptable behavior by participants include:

* The use of sexualized language or imagery and unwelcome sexual attention or
advances
* Trolling, insulting/derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or electronic
  address, without explicit permission
* Other conduct which could reasonably be considered inappropriate in a
  professional setting

### Our Responsibilities {-}

Project maintainers are responsible for clarifying the standards of acceptable
behavior and are expected to take appropriate and fair corrective action in
response to any instances of unacceptable behavior.

Project maintainers have the right and responsibility to remove, edit, or
reject comments, commits, code, wiki edits, issues, and other contributions
that are not aligned to this Code of Conduct, or to ban temporarily or
permanently any contributor for other behaviors that they deem inappropriate,
threatening, offensive, or harmful.

### Scope {-}

This Code of Conduct applies both within project spaces and in public spaces
when an individual is representing the project or its community. Examples of
representing a project or community include using an official project e-mail
address, posting via an official social media account, or acting as an appointed
representative at an online or offline event. Representation of a project may be
further defined and clarified by project maintainers.

### Enforcement {-}

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the project team. All complaints will be reviewed and 
investigated and will result in a response that is deemed necessary and
appropriate to the circumstances. The project team is obligated to maintain
confidentiality with regard to the reporter of an incident.
Further details of specific enforcement policies may be posted separately.

Project maintainers who do not follow or enforce the Code of Conduct in good
faith may face temporary or permanent repercussions as determined by other
members of the project's leadership.

### Attribution {-}

This Code of Conduct is adapted from the [Contributor Covenant][homepage], version 1.4,
available at [http://contributor-covenant.org/version/1/4][version]

[homepage]: http://contributor-covenant.org
[version]: http://contributor-covenant.org/version/1/4/
