# Model Scoping

> Microsimulation is like a microscope.
It is a very effective tool when you have it pointed at the correct subject.
Tightly focused scopes of work ensure cost-effective microsimulation analyses.
<br>
*--From the FHWA Traffic Analysis Toolbox Volume 3*

The "micro" in microsimulation tells you everything you need to know:

- Micro as in: the simulation deals with the small interactions between vehicles.
- Micro as in: **keep the model small**.

Keeping things small is a reocurring theme in scoping because resources are finite.
So small that it is worthwhile to consider:

- [Do you Need A Model at All?]
- [Should you use Microsimulation?]
- [Other Questions](#Other-Questions)

## Do you Need A Model at All?

If a project being scoped is tackling an observable issue, collecting and analyzing field data may be enough to make a decision (analysis does not have to equal modeling). For example:

 - *Problem:* A temporary work zone is observed to cause queues about an hour before opening to traffic. *Analysis:* Collect volume and queue data, try shifting work zone hours to times with lower volumes.
 - *Problem:* A freeway with several closely-spaced on-ramps experiences congestion. *Analysis:* Collect volume and speed data. Look at the potential for alternate routes. Close a ramp and collect data during the closure to see the problem is improved. 

The above freeway example may seem bold by conducting live experiments in the field. **Field data always beats model results.** If alternatives are "subtractive" (i.e. taking away something, like a lane, ramp, signals, etc), putting out construction barrels to try out an idea will always result in better results than a model. Real drivers will be reacting to real field conditions instead of hypothetical modeled condtions. Field experimentation may be faster and more effective than developing models because seeing is believing. The same goes for "low-risk" alternatives such as trying a mini-roundabout in a neighborhood. Do public outreach, put out some barrels, and give it a try.

## Should you use Microsimulation?
Consider an analogy to signal warrants: Traffic signal warrants are as much about preventing installation of unnecessary signals as they are about helping determine when traffic signals are appropriate. While there are no formal "microsimulation warrants," the following questions will help guide you to determine if microsimulation may be useful and prevent you from many headaches. Microsimulation *may* be useful if you answer **YES** to any of the following:

 - Existing or alternative scenarios cannot be modeled without microsimulation (i.e.  simpler analysis tools are available for analyzing the scenarios).
 - Non-microsimulation tools will not provide the degree of precision required for the project objectives.
 - Experienced staff can commit extensive time to the project to deal with the complexity and data challenges that come with simulation
 - Time and budget will allow for detailed calibration of existing conditions.
 - Time and budget will allow for error checking and multiple simulation runs.
 - The area of interest has limited spatial and temporal extents to allow for reasonable compute times per run.
   - If the purpose is to answer "big picture," or network-wide effects, microsimulation is probably not the best choice. Large-scale alternatives may also rule out microsimulation. Knowing the purpose helps scope the right type of model and model limits.
 - The number of scnearios to simulate is small (for example: existing year, future no-build, 1 alternative).
 - The scope is well defined and a plan is in place to manage scope creep.

If you have made it this far and decided that *yes* a model is needed, and *yes* microsimulation is the most likely tool, there are still more questions to consider for scoping. These questions may or may not change your mind about using microsimulation.

## Additional Questions to Consider when Scoping {#Other-Questions}

### What is the Model purpose?
Models are not the only factor in the decision making process. Physical, financial, environmental, and other factors often play more important roles than traffic models. However, models do serve a purpose:

- **Models help with complex alternative analysis.** When alternatives cannot be safely or efficently field tested, modeling can help evaluate alternatives. Having an idea of what alternatives may be considered helps with scoping.
- **Models are conversation pieces.** Models provide something to talk about when discussing existing conditions and alternatives. Detailed modeling involves gathering data and having discussions, which can be more important than the model results themselves. If the model gets people talking about problems and ideas, then the model has probably been worthwhile, even if it has limitations.

### What question(s) will the model answer?
Related to model purpose, asking a specific question of the model helps to scope the right model extents. The more focused the question, the better for microsimulation. Asking "how will changing this weaving configuration affect throughput?" is a better question than something more generic like "what is the Level of Service?" Generic questions can likely be answered by more efficient means than microsimulation.

### What data is available?
Lack of field data can rule out microsimulation, or severely limit its accuracy. Without field data, model calibration may not be achievable, which detracts from the models believability.

### What scenarios are being considered?
Just existing year? Future years? Each scenario increases the time effort to complete the microsimulation. Limit the number of scenarios during scoping. For example consider analyzing only one or two alternatives with microsimulation. Small variations of one alternative may not be worthwhile to simulate.

### What are the model spatial limits?
TODO

### What are the model temporal limits?
TODO

### What is the model output / performance measures?
TODO
